
return {
  art1 = "information: HC - Matthias Richter",
  art2 = "information: STI - Landon Manning",
  art3 = "information: json.lua - rxi",
  lp0OutOfPaper = "error: lp0 is not a printer",
  nominal = "information: this is probably a door",
  powerOn = "information: flying saucer power is on",
  powerOff = "information: flying saucer power is off",
  rebooting = "clive@Saucer:~$",
  bridge = "information: like a bridge over running water I will be no use",
  
  runScreaming = "Well that seems to have worked itself out",
  youCanRead = "If you can read this, you are not able to read, but you are gullible. Well done!",
  inTheEvent = "Warning: self help books may not be very effective",
  warningJumping = "Warning: jumping and climbing can be dangerous",
  youHaveNoIdea = "If I told you you were crazy, would you stop reading this sign?",
  involvedIn = "Involved in a flying saucer accident that was not your fault?\n"..
    "Sucks to be you...",
  areYouSure = "Are you sure you want to turn your flying saucer off?",
  asASafetyFeature = "As a safety feature, access to power reset is still really stupid",
  observationRoomNote = "I give up. Do whatever you want to the observation deck.",
  chargerNote = "Fuel Barrel Goes Here",
  
  signToEngines = "to engines and stuff",
  signBridge = "bridge",
  signToEscapePodRun = "escape saucer",
  signToEscapePod = "to escape saucer",
  signToBoring = "to the rest of the saucer",
  signToSafety = "nope, no cookies that way",
  signToBridgeAndPod = "to bridge and escape saucer",
  signToEngines = "to engineering",
  signBasement = "like boxes and stuff",
  signToReset = "main power reset",
}